name: Bug Report
description: Report something that is not working as expected.
title: "[BUG] "
labels: [ "bug report" ]
body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to submit a bug report. 
        Please search to ensure that the bug has not already been reported.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: > 
        A clear and concise description of the bug. A description of the issue using key words 
        relating to the issue. 50 to 80 characters recommended. Description should cover the 
        problem, the action, and the location (if relevant).
  - type: textarea
    id: reproduction
    attributes:
      label: Steps
      description: The steps to reproduce the behaviour
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
  - type: textarea
    id: expectation
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
  - type: upload
    id: uploads
    attributes:
      label: Uploads
      description: > 
        Provide screenshots or recordings to explain your problem. If the bug is only 
        encountered when using specific test data, provide a copy of that data. If the 
        data needs to be redacted, please ensure the redacted data also causes the 
        unexpected behavior using the same steps.
    validations:
      accept: ".png,.jpg,.jpeg,.gif,.svg,.webp,.mp4,.mov,.webm"
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: The operating system, Python version, software version in use where relevant.
      placeholder: |
        OS: Windows 11 build 26200.8246
        Interpreter: Python 3.14.1
        Version: 0.1.0
  - type: textarea
    id: details
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
